<?php

namespace App\Console\Commands;

use Illuminate\Console\Command;

/**
 * Verify (and optionally rewrite) per-directory PHP upload limits for APK uploads.
 */
class AppReleasesEnsurePhpLimitsCommand extends Command
{
    protected $signature = 'app-releases:ensure-php-limits
        {--write : Rewrite public/.user.ini and project .user.ini with 500M limits}';

    protected $description = 'Check PHP upload limits for APK web uploads; optionally rewrite .user.ini files.';

    private const UPLOAD_MB = 500;

    private const POST_MB = 520;

    public function handle(): int
    {
        $upload = ini_get('upload_max_filesize');
        $post = ini_get('post_max_size');
        $uploadMb = $this->iniToMb($upload);
        $postMb = $this->iniToMb($post);

        $this->line('Current PHP limits (this CLI process):');
        $this->line('  upload_max_filesize = '.($upload ?: 'unknown').($uploadMb ? " ({$uploadMb} MB)" : ''));
        $this->line('  post_max_size       = '.($post ?: 'unknown').($postMb ? " ({$postMb} MB)" : ''));

        if ($this->option('write')) {
            $contents = $this->iniFileContents();
            foreach ([public_path('.user.ini'), base_path('.user.ini'), public_path('php.ini')] as $path) {
                if (@file_put_contents($path, $contents) !== false) {
                    $this->info('Wrote '.$path);
                } else {
                    $this->warn('Could not write '.$path.' (check permissions).');
                }
            }
            $this->line('');
            $this->comment('Web limits refresh within ~5 minutes (.user.ini cache). Reload the app-releases page to verify.');
        }

        $ready = $uploadMb !== null
            && $uploadMb >= self::UPLOAD_MB
            && ($postMb === null || $postMb >= self::UPLOAD_MB);

        if ($ready) {
            $this->info('Upload limits look sufficient for '.self::UPLOAD_MB.' MB APKs.');

            return self::SUCCESS;
        }

        $this->warn('Limits are still below '.self::UPLOAD_MB.' MB for the web SAPI.');
        $this->line('In cPanel → MultiPHP INI Editor (domain at-enda.manuelcode.info), set:');
        $this->line('  upload_max_filesize = '.self::UPLOAD_MB.'M');
        $this->line('  post_max_size       = '.self::POST_MB.'M');
        $this->line('Then run: php artisan app-releases:ensure-php-limits --write');
        $this->line('If uploads still fail with 503, ask the host to set nginx client_max_body_size 520m.');

        return self::FAILURE;
    }

    private function iniFileContents(): string
    {
        return implode("\n", [
            '; Auto-generated by app-releases:ensure-php-limits',
            'upload_max_filesize = '.self::UPLOAD_MB.'M',
            'post_max_size = '.self::POST_MB.'M',
            'max_execution_time = 600',
            'max_input_time = 600',
            'memory_limit = 512M',
            '',
        ]);
    }

    private function iniToMb(string|false $value): ?float
    {
        if (! is_string($value) || $value === '') {
            return null;
        }

        $value = trim($value);
        if (is_numeric($value)) {
            return round(((float) $value) / 1024 / 1024, 1);
        }

        $unit = strtolower(substr($value, -1));
        $number = (float) substr($value, 0, -1);

        $bytes = match ($unit) {
            'g' => $number * 1024 * 1024 * 1024,
            'm' => $number * 1024 * 1024,
            'k' => $number * 1024,
            default => (float) $value,
        };

        return round($bytes / 1024 / 1024, 1);
    }
}
